version: '3.9'

networks:
  eksplorasi-laravel:
    name: eksplorasi-laravel

services:
  webserver:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:pro
    volumes_from:
      - php
    depends_on:
      - php
      - db
    networks:
      - eksplorasi-laravel

  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_velo_eksplorasi
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: password
      SERVICE_NAME: mysql
      SERVICE_TAG: dev
    restart: unless-stopped
    tty: true
    networks:
      - eksplorasi-laravel
  
  php:
    image: php:8-fpm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    networks:
      - eksplorasi-laravel

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - mysql
    restart: always
    networks:
      - eksplorasi-laravel